src/objects/Payment_Processor__c.object
<CustomObject>
    <fields>
        <fullName>API_Login_Id__c</fullName>
        <inlineHelpText>Authorize.Net only, required API Login Id</inlineHelpText>
        <label>API Login Id</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>API_Password__c</fullName>
        <inlineHelpText>Paypal only, required password</inlineHelpText>
        <label>API Password</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>API_Signature__c</fullName>
        <inlineHelpText>Paypal only, required signature</inlineHelpText>
        <label>API Signature</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>API_Username__c</fullName>
        <inlineHelpText>Paypal only, required username field</inlineHelpText>
        <label>API Username</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Default_Connection__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box to use this payment processor connection by default when there are multiple connections available.</inlineHelpText>
        <label>Default Connection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Processor__c</fullName>
        <inlineHelpText>The payment gateway/processor to which these API credentials apply</inlineHelpText>
        <label>Payment Processor</label>
        <picklist>
            <picklistValues>
                <fullName>Authorize.Net</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sandbox__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box for test accounts so they will log into the Sandbox URL for API access. If this option is not set properly, your API login will fail.</inlineHelpText>
        <label>Sandbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transaction_Key__c</fullName>
        <inlineHelpText>Authorize.Net only, required Transaction Key</inlineHelpText>
        <label>Transaction Key</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PaymentApiConfig.cls
global with sharing class PaymentApiConfig {

	global Payment_Processor__c defaultProcessor { get; private set; }	
	global map<string,Payment_Processor__c> processorMap { get; private set; }
		
	global PaymentApiConfig() {
        //instantiate map
        processorMap = new map<string,Payment_Processor__c>();
        
        // load payment processor settings and find the default
        list<Payment_Processor__c> processorsList = [SELECT Name, API_Login_Id__c, API_Password__c, API_Signature__c, API_Username__c, 
        						Default_Connection__c, Payment_Processor__c, Sandbox__c, Transaction_Key__c
        						FROM Payment_Processor__c ORDER BY LastModifiedDate];
        if (!processorsList.isEmpty()) {
	        for (Payment_Processor__c processor : processorsList) {
	        	processorMap.put(processor.Name,processor);
	            if (processor.default_connection__c == true) {
	                defaultProcessor = processor;
	            }
	        }
        } 
        	
	}
	
	global string getProcessor(string configName) {
		//returns the type of processor, PayPal or Authorize.Net
		Payment_Processor__c processor = processorMap.containsKey(configName) ? processorMap.get(configName) : defaultProcessor;
		if (processor != null) {
			return processor.Payment_Processor__c;
		} else {
			return null;
		}
	}
	
    global OnlinePayment.APIAuthorization getAuth( string configName ) {

        OnlinePayment.APIAuthorization auth;
       	Payment_Processor__c processor = processorMap.containsKey(configName) ? processorMap.get(configName) : defaultProcessor;
  		if (processor != null) {
	        if (processor.Payment_Processor__c == 'PayPal') {
	            auth = new OnlinePayment.APIAuthorization(
	                processor.API_Username__c, processor.API_Password__c, processor.API_Signature__c, 
	                OnlinePayment.getRemoteHost(), processor.sandbox__c 
	            );
	        } else {
	        	//we're using Authorize.Net
	        	auth = new OnlinePayment.APIAuthorization(
	                processor.API_Login_Id__c, processor.Transaction_Key__c, null, 
	                OnlinePayment.getRemoteHost(), processor.Sandbox__c 
	            );
	        }
  		}
        return auth;

    }    
    
}