src/objects/Payment_Processor__c.object
<CustomObject>
    <fields>
        <fullName>Default_Connection__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box to use this payment processor connection by default when there are multiple connections available.</inlineHelpText>
        <label>Default Connection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Processor__c</fullName>
        <inlineHelpText>The payment gateway/processor to which these API credentials apply</inlineHelpText>
        <label>Payment Processor</label>
        <picklist>
            <picklistValues>
                <fullName>Authorize.Net</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TEST_ProcessorPreventTwoDefaults.cls
@isTest (SeeAllData=true)
private class TEST_ProcessorPreventTwoDefaults {
	
	static testmethod void addSecondDefault() {
		
		//find and delete existing default processors
		Payment_Processor__c[] existingDefaults = [SELECT id FROM Payment_Processor__c WHERE Default_Connection__c = true];
		if (!existingDefaults.isEmpty()) {
			delete existingDefaults;
		}
		
		Payment_Processor__c defaultProcessor = new Payment_Processor__c(
			Name = 'Default_Processor',
			Default_Connection__c = true,
			Payment_Processor__c = 'PayPal'
			);
		insert defaultProcessor;
		
		Payment_Processor__c secondDefault = new Payment_Processor__c(
			Name = 'Second_Default_Processor',
			Default_Connection__c = true,
			Payment_Processor__c = 'PayPal'
			);
		
		try {
			insert secondDefault;
		} catch (Exception e) {
			system.assert(e.getMessage().contains('You have already selected a Payment Processor as the Default Processor.'));
		}
		
	}
	
}